security:

    encoders:
        DCS\User\CoreBundle\Model\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        dcs_user:
            id: dcs_security.core.provider.user

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            dcs_form:
                provider: dcs_user
                csrf_token_generator: security.csrf.token_manager
                login_path: dcs_security_login
                check_path: dcs_security_login_check
            logout:
                path:   dcs_security_logout
                target: /
            anonymous: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/password-reset, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }